from typing import Protocol


class KnowledgeGraphStore(Protocol):
    async def stats(self) -> dict: ...

    async def search_stats(self, query: str) -> dict: ...

    async def list_entities(self, **filters) -> tuple[list[dict], int]: ...

    async def entity_filter_options(self) -> dict[str, list[str]]: ...

    async def get_entity(self, entity_id: str, **limits) -> dict | None: ...

    async def add_relationship(self, entity_id: str, relationship: str, to_entity_id: str, source: str | None, recommendations: dict | None) -> dict | None: ...

    async def update_relationship(self, entity_id: str, relationship_id: int, relationship: str, to_entity_id: str, source: str | None, recommendations: dict | None, *, from_entity_id: str | None = None) -> dict | None: ...

    async def delete_relationship(self, entity_id: str, relationship_id: int) -> bool: ...

    async def create_entity(self, **payload) -> dict: ...

    async def update_entity(self, entity_id: str, **payload) -> dict | None: ...

    async def delete_entity(self, entity_id: str) -> bool: ...

    async def list_auto_attach_rules(self) -> list[dict]: ...

    async def upsert_auto_attach_rule(self, **payload) -> dict: ...

    async def delete_auto_attach_rule(self, rule_id: str) -> bool: ...

    async def list_auto_attach_aliases(self) -> list[dict]: ...

    async def upsert_auto_attach_alias(self, **payload) -> dict: ...
