-- Extend reviewed aliases through the current Hanoi generic TravelPlace top 60.
-- Only known-corrupt aliases are removed; valid imported aliases are preserved.
BEGIN;

DELETE FROM knowledge_aliases
WHERE entity_id = ANY(ARRAY[
    'travel_place_ChIJh3K0K1RhNDEREXbFmPaEF_w',
    'travel_place_ChIJMyhkeCBTNDERlwTFwiG82wE',
    'travel_place_ChIJ9Y3KR7-rNTERawQ7FeFv5gA',
    'travel_place_ChIJA9hjcdurNTER__fyEGdqfGM',
    'travel_place_ChIJlx8obZWrNTERa7Mn6ghQJ6Q',
    'travel_place_ChIJY2LZEqOrNTERXP_uKG1UBzc',
    'travel_place_ChIJzxoUuR-sNTER7LqJfFg2QC0',
    'travel_place_ChIJccun9eurNTERtKVn44HT8Ig',
    'travel_place_ChIJA27-IoarNTERTHKK_dS8MPE',
    'travel_place_ChIJ3x01HQCrNTERtBCN9T55LnI',
    'travel_place_ChIJefmI_YirNTERUBrJAy78Hrw',
    'travel_place_ChIJl-gkmYKrNTERVsfrJs8ODZ8',
    'travel_place_ChIJ902h-p6rNTERsrEvnlSnDDU',
    'entertainment_dessert_ChIJ__9v1LqrNTERw6DdpcC6Lsg',
    'travel_place_ChIJZb89JrmrNTERA5SN2uMsizU',
    'travel_place_ChIJ_WxOh-aqNTERU3pju0DhjDE',
    'travel_place_ChIJK2QyG-2zNTER2d2FUFvqHps',
    'travel_place_ChIJlU5xE06sNTERaVEkkwfV4YI',
    'travel_place_ChIJz0aH0VyrNTERrhRrKTcIFxk',
    'travel_place_ChIJS7GypZWrNTERr2jliTrPBTI',
    'travel_place_ChIJwyFZi6WrNTER76sqY7OcMjE',
    'travel_place_ChIJP_qrg_KrNTERnOWkD67p0p8',
    'travel_place_ChIJxZVbuqKrNTER4I2XSRfxbLg'
]::text[])
  AND (
      alias LIKE '%?%'
      OR alias IN (
          'vddn qudc gia ba vd',
          'ddn bia bd',
          'ddn bdch md',
          'chda bd dd',
          'tddng ddi bdc sdn',
          'chd ddm ldnh nam',
          'qudng trddng cdch mdng thdng tdm',
          'hd ba mdu',
          'didm bdt ddu chd ddm cudi tudn hd ndi',
          'hd bdy mdu',
          'chda didn hdu',
          'chda mdt cdt',
          'bdch cdu ddo qudn'
      )
  );

INSERT INTO knowledge_aliases(
    entity_id, alias, normalized_alias, language, source
)
VALUES
    ('travel_place_ChIJh3K0K1RhNDEREXbFmPaEF_w',
     'Vườn Quốc gia Ba Vì', 'vuon quoc gia ba vi', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJh3K0K1RhNDEREXbFmPaEF_w',
     'Ba Vì National Park', 'ba vi national park', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJMyhkeCBTNDERlwTFwiG82wE',
     'Đền Bia Bà', 'den bia ba', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJMyhkeCBTNDERlwTFwiG82wE',
     'Bia Bà Temple', 'bia ba temple', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ9Y3KR7-rNTERawQ7FeFv5gA',
     'Đền Bạch Mã', 'den bach ma', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ9Y3KR7-rNTERawQ7FeFv5gA',
     'Bạch Mã Temple', 'bach ma temple', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJK111AwurNTERB8u6Ap8YDjg',
     'Bảo tàng Chiến thắng B-52', 'bao tang chien thang b 52', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJK111AwurNTERB8u6Ap8YDjg',
     'B-52 Victory Museum', 'b 52 victory museum', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJA9hjcdurNTER__fyEGdqfGM',
     'Chùa Bồ Đề', 'chua bo de', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJA9hjcdurNTER__fyEGdqfGM',
     'Bồ Đề Pagoda', 'bo de pagoda', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJlx8obZWrNTERa7Mn6ghQJ6Q',
     'Chùa Bà Đá', 'chua ba da', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJlx8obZWrNTERa7Mn6ghQJ6Q',
     'Bà Đá Pagoda', 'ba da pagoda', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJY2LZEqOrNTERXP_uKG1UBzc',
     'Đài tưởng niệm Bắc Sơn', 'dai tuong niem bac son', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJY2LZEqOrNTERXP_uKG1UBzc',
     'Bắc Sơn Monument', 'bac son monument', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJzxoUuR-sNTER7LqJfFg2QC0',
     'Chợ đêm Lĩnh Nam', 'cho dem linh nam', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJzxoUuR-sNTER7LqJfFg2QC0',
     'Lĩnh Nam Night Market', 'linh nam night market', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJccun9eurNTERtKVn44HT8Ig',
     'Quảng trường Cách mạng Tháng Tám',
     'quang truong cach mang thang tam', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJccun9eurNTERtKVn44HT8Ig',
     'August Revolution Square', 'august revolution square', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJA27-IoarNTERTHKK_dS8MPE',
     'Hồ Ba Mẫu', 'ho ba mau', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJA27-IoarNTERTHKK_dS8MPE',
     'Ba Mẫu Lake', 'ba mau lake', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ3x01HQCrNTERtBCN9T55LnI',
     'Điểm bắt đầu Chợ đêm cuối tuần Hà Nội',
     'diem bat dau cho dem cuoi tuan ha noi', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ3x01HQCrNTERtBCN9T55LnI',
     'Chợ đêm Phố cổ Hà Nội', 'cho dem pho co ha noi', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ3x01HQCrNTERtBCN9T55LnI',
     'Hanoi Old Quarter Night Market', 'hanoi old quarter night market', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJefmI_YirNTERUBrJAy78Hrw',
     'Hồ Bảy Mẫu', 'ho bay mau', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJefmI_YirNTERUBrJAy78Hrw',
     'Bảy Mẫu Lake', 'bay mau lake', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJl-gkmYKrNTERVsfrJs8ODZ8',
     'Chùa Diên Hựu', 'chua dien huu', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJl-gkmYKrNTERVsfrJs8ODZ8',
     'Diên Hựu Pagoda', 'dien huu pagoda', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ902h-p6rNTERsrEvnlSnDDU',
     'Bích Câu Đạo Quán', 'bich cau dao quan', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ902h-p6rNTERsrEvnlSnDDU',
     'Bich Cau Dao Quan', 'bich cau dao quan', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJwYrhVWeqNTERWKke9kRAasc',
     'Vườn hoa Bãi đá Sông Hồng', 'vuon hoa bai da song hong', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJpwaPRbCrNTERZqy0vKOvxyY',
     'Bookworm Bookshop', 'bookworm bookshop', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJpwaPRbCrNTERZqy0vKOvxyY',
     'Bookworm Hanoi Bookshop', 'bookworm hanoi bookshop', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJZb89JrmrNTERA5SN2uMsizU',
     'Thánh đường Hồi giáo Al-Noor',
     'thanh duong hoi giao al noor', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJZb89JrmrNTERA5SN2uMsizU',
     'Al-Noor Mosque', 'al noor mosque', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJZb89JrmrNTERA5SN2uMsizU',
     'Al-Noor Mosque Hanoi', 'al noor mosque hanoi', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJja32kfGxNTERuTwJJ1D-UOw',
     'Nhà thờ Bằng Sở', 'nha tho bang so', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJja32kfGxNTERuTwJJ1D-UOw',
     'Giáo xứ Bằng Sở', 'giao xu bang so', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJja32kfGxNTERuTwJJ1D-UOw',
     'Đền thánh Phêrô Lê Tùy', 'den thanh phero le tuy', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ_WxOh-aqNTERU3pju0DhjDE',
     'Chùa Vạn Niên', 'chua van nien', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ_WxOh-aqNTERU3pju0DhjDE',
     'Vạn Niên Pagoda', 'van nien pagoda', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ87nIRg-1NTERVWUTnYO80s0',
     'Làng hương Quảng Phú Cầu', 'lang huong quang phu cau', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ87nIRg-1NTERVWUTnYO80s0',
     'Quảng Phú Cầu Incense Village',
     'quang phu cau incense village', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJK2QyG-2zNTER2d2FUFvqHps',
     'Chùa Đậu', 'chua dau', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJK2QyG-2zNTER2d2FUFvqHps',
     'Đậu Pagoda', 'dau pagoda', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJlU5xE06sNTERaVEkkwfV4YI',
     'Chùa Pháp Vân', 'chua phap van', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJlU5xE06sNTERaVEkkwfV4YI',
     'Pháp Vân Pagoda', 'phap van pagoda', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJz0aH0VyrNTERrhRrKTcIFxk',
     'Chùa Láng', 'chua lang', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJz0aH0VyrNTERrhRrKTcIFxk',
     'Láng Pagoda', 'lang pagoda', 'en', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJVUvVbACrNTERzY_ZFRXbAKc',
     'Xe buýt hai tầng Hà Nội', 'xe buyt hai tang ha noi', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJVUvVbACrNTERzY_ZFRXbAKc',
     'Hanoi Hop On Hop Off Bus', 'hanoi hop on hop off bus', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJSYLs8I5hNDERHuG4hAXYxsg',
     'Khu di tích K9 Đá Chông', 'khu di tich k9 da chong', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJSYLs8I5hNDERHuG4hAXYxsg',
     'K9 Đá Chông', 'k9 da chong', 'vi', 'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJSYLs8I5hNDERHuG4hAXYxsg',
     'K9 Historical Site', 'k9 historical site', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJE109t6KrNTERsaAoYzbvoKY',
     'Bảo tàng Lịch sử Quân sự Việt Nam',
     'bao tang lich su quan su viet nam', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJE109t6KrNTERsaAoYzbvoKY',
     'Vietnam Military History Museum Hanoi',
     'vietnam military history museum hanoi', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJfYlEhARaNDERfUqU02_fDo8',
     'Chùa Tây Phương', 'chua tay phuong', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJfYlEhARaNDERfUqU02_fDo8',
     'Tây Phương Pagoda', 'tay phuong pagoda', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJJ2JpFQCrNTERqi11c3UpJjg',
     'Bảo tàng Phụ nữ Việt Nam', 'bao tang phu nu viet nam', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJJ2JpFQCrNTERqi11c3UpJjg',
     'Vietnam Women''s Museum', 'vietnam women s museum', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJp-96zQb2NDERsdAD--zhil4',
     'Thành cổ Sơn Tây', 'thanh co son tay', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJp-96zQb2NDERsdAD--zhil4',
     'Sơn Tây Ancient Citadel', 'son tay ancient citadel', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJp-96zQb2NDERsdAD--zhil4',
     'Son Tay Citadel', 'son tay citadel', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJwyFZi6WrNTER76sqY7OcMjE',
     'Đền Quán Thánh', 'den quan thanh', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJwyFZi6WrNTER76sqY7OcMjE',
     'Quán Thánh Temple', 'quan thanh temple', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ9dt7lJirNTERTqzApIMfQv0',
     'Bảo tàng Mỹ thuật Việt Nam', 'bao tang my thuat viet nam', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ9dt7lJirNTERTqzApIMfQv0',
     'Vietnam Fine Arts Museum', 'vietnam fine arts museum', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ9dt7lJirNTERTqzApIMfQv0',
     'Vietnam National Museum of Fine Arts',
     'vietnam national museum of fine arts', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJP_qrg_KrNTERnOWkD67p0p8',
     'Nhà thờ Hàm Long', 'nha tho ham long', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJP_qrg_KrNTERnOWkD67p0p8',
     'Nhà thờ Thánh Antôn Hàm Long',
     'nha tho thanh anton ham long', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJP_qrg_KrNTERnOWkD67p0p8',
     'Hàm Long Church', 'ham long church', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ8S--CRIzNDER4EBfws0rMNU',
     'Chùa Thiên Trù', 'chua thien tru', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJ8S--CRIzNDER4EBfws0rMNU',
     'Thiên Trù Pagoda', 'thien tru pagoda', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJo7Cs_7IANTER3jarOmtDKpU',
     'Khu di tích Cổ Loa', 'khu di tich co loa', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJo7Cs_7IANTER3jarOmtDKpU',
     'Cổ Loa Citadel', 'co loa citadel', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJo7Cs_7IANTER3jarOmtDKpU',
     'Co Loa Citadel', 'co loa citadel', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJxZVbuqKrNTER4I2XSRfxbLg',
     'Cột cờ Hà Nội', 'cot co ha noi', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJxZVbuqKrNTER4I2XSRfxbLg',
     'Kỳ đài Hà Nội', 'ky dai ha noi', 'vi',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJxZVbuqKrNTER4I2XSRfxbLg',
     'Hanoi Flagpole', 'hanoi flagpole', 'en',
     'manual_alias_curation:2026-08-21'),
    ('travel_place_ChIJxZVbuqKrNTER4I2XSRfxbLg',
     'Flag Tower of Hanoi', 'flag tower of hanoi', 'en',
     'manual_alias_curation:2026-08-21')
ON CONFLICT (entity_id, alias) DO UPDATE
SET normalized_alias = EXCLUDED.normalized_alias,
    language = EXCLUDED.language,
    source = EXCLUDED.source;

COMMIT;
