from __future__ import annotations

import asyncio
import json

import pytest

from app.modules.places.auto_statistics.service import (
    PlannerRegionStatisticsResult,
)
from app.modules.plans.domain.entities import TravelIntent
from app.modules.plans.domain.enums import BudgetLevel, TravelPace
from app.modules.plans.dto.agent_contracts import (
    PlanWorkingState,
    SelectedPlaceContext,
    TripPlanningSpec,
)
from app.modules.plans.planner.planner_service import PlannerService
from app.modules.plans.planner.region_context import normalize_region_key
from app.modules.plans.checks.backup_validator import BackupValidator
from app.modules.plans.checks.overall_checker import OverallChecker
from app.modules.plans.explorer.explorer_service import ExplorerService
from app.modules.plans.finder.finder_service import FinderService
from app.modules.plans.schema import (
    BackupPlanCreate,
    MainPlanCreate,
    MainPlanFromExplorerCreate,
    PlanningContextCreate,
    SelectedPlaceCreate,
)
from app.modules.plans.repository import PlanRepository
from app.modules.plans.service import PlanService
from app.modules.plans.workflows.backup_plan_workflow import BackupPlanWorkflow
from app.modules.plans.workflows.main_plan_workflow import MainPlanWorkflow
from app.shared.errors import AppError


def test_normalize_region_key_from_vietnamese_destination() -> None:
    assert normalize_region_key("Hà Nội") == "vn,ha-noi"
    assert normalize_region_key("ignored", "vn,hai-phong") == "vn,hai-phong"


def test_planner_uses_snapshot_and_accounts_for_selected_places() -> None:
    statistics = FakeStatisticsProvider()
    service = _planner(statistics)
    selected_places = [
        SelectedPlaceContext(
            name="Văn Miếu",
            placeId="place-van-mieu",
            mustVisit=True,
            priority=1,
        ),
        SelectedPlaceContext(
            name="Bỏ qua",
            placeId="place-excluded",
            priority=2,
        ),
    ]

    output = asyncio.run(
        service.create_main_macro_plan(
            _intent(),
            trip_spec=TripPlanningSpec(days=2),
            region_key="vn,ha-noi",
            selected_places=selected_places,
            plan_state=PlanWorkingState(excludedPlaceNames=["Bỏ qua"]),
        )
    )

    assert statistics.requested_region_keys == ["vn,ha-noi"]
    assert output.day_briefs_ready is True
    assert "snapshotRef" not in output.macro_plan.model_dump(by_alias=True)
    assert "generator=llm" in output.trace.notes
    assert "promptVersion=macro_planner_v1" in output.trace.notes
    assert "snapshotId=snapshot-3" in output.trace.notes
    assert output.macro_plan.day_briefs[0].target_region_key == (
        "vn,ha-noi,hoan-kiem"
    )
    assert output.macro_plan.day_briefs[0].focus_tags[:2] == [
        "culture",
        "food",
    ]
    assert output.macro_plan.day_briefs[0].allocated_selected_place_refs == [
        "place-van-mieu"
    ]
    assert output.unallocated_selected_places[0].place.place_id == (
        "place-excluded"
    )
    assert output.unallocated_selected_places[0].reason_code == (
        "excluded_by_plan_state"
    )
    assert output.assumptions == ["Generated by test LLM."]


def test_planner_marks_day_briefs_not_ready_when_region_is_empty() -> None:
    service = _planner(FakeStatisticsProvider(place_count=0))

    output = asyncio.run(
        service.create_main_macro_plan(
            _intent(),
            trip_spec=TripPlanningSpec(days=2),
            region_key="vn,ha-noi",
            selected_places=[],
        )
    )

    assert output.day_briefs_ready is False
    assert output.trace.status.value == "blocked"
    assert output.warnings == [
        "Không có Place active cho vn,ha-noi; Finder chỉ có thể dùng các "
        "địa điểm người dùng đã chọn."
    ]


def test_planner_sends_small_area_statistics_to_llm() -> None:
    llm = RecordingPlannerLLM()
    service = PlannerService(FakeStatisticsProvider(), llm)

    asyncio.run(
        service.create_main_macro_plan(
            _intent(),
            trip_spec=TripPlanningSpec(days=2),
            region_key="vn,ha-noi",
            selected_places=[],
        )
    )

    assert "Macro Planner" in llm.system_prompt
    payload = json.loads(llm.user_payload)
    assert payload["promptVersion"] == "macro_planner_v1"
    assert payload["plannerInput"]["regionContext"]["plannerSignals"][
        "candidateAreas"
    ][0]["regionKey"] == "vn,ha-noi,hoan-kiem"


def test_planner_can_continue_without_catalog_when_places_are_confirmed() -> None:
    service = _planner(FakeStatisticsProvider(place_count=0))

    output = asyncio.run(
        service.create_main_macro_plan(
            _intent(),
            trip_spec=TripPlanningSpec(days=1),
            region_key="vn,ha-noi",
            selected_places=[
                SelectedPlaceContext(
                    placeId="place-van-mieu",
                    name="Văn Miếu",
                    mustVisit=True,
                )
            ],
        )
    )

    assert output.day_briefs_ready is True
    assert output.macro_plan.day_briefs[0].allocated_selected_place_refs == [
        "place-van-mieu"
    ]


def test_planner_reports_confirmed_places_over_day_capacity() -> None:
    service = _planner(FakeStatisticsProvider())
    selected_places = [
        SelectedPlaceContext(
            placeId=f"place-{index}",
            name=f"Place {index}",
            mustVisit=True,
        )
        for index in range(1, 8)
    ]

    output = asyncio.run(
        service.create_main_macro_plan(
            _intent(),
            trip_spec=TripPlanningSpec(days=2),
            region_key="vn,ha-noi",
            selected_places=selected_places,
        )
    )

    allocated = sum(
        len(day.allocated_selected_place_refs)
        for day in output.macro_plan.day_briefs
    )
    assert allocated == 6
    assert output.unallocated_selected_places[0].place.place_id == "place-7"
    assert output.unallocated_selected_places[0].reason_code == "no_day_capacity"


def test_planner_does_not_allocate_explicitly_avoided_place() -> None:
    service = _planner(FakeStatisticsProvider())
    intent = _intent().model_copy(
        update={"avoid_places": ["Avoid Me"]}
    )

    output = asyncio.run(
        service.create_main_macro_plan(
            intent,
            trip_spec=TripPlanningSpec(days=1),
            region_key="vn,ha-noi",
            selected_places=[
                SelectedPlaceContext(
                    placeId="avoid-me",
                    name="Avoid Me",
                    mustVisit=True,
                )
            ],
        )
    )

    assert output.macro_plan.day_briefs[0].allocated_selected_place_refs == []
    assert output.unallocated_selected_places[0].place.place_id == "avoid-me"
    assert output.unallocated_selected_places[0].reason_code == "avoided_by_user"


def test_planner_is_ready_with_confirmed_place_when_region_is_empty() -> None:
    service = _planner(FakeStatisticsProvider(place_count=0))

    output = asyncio.run(
        service.create_main_macro_plan(
            _intent(),
            trip_spec=TripPlanningSpec(days=2),
            region_key="vn,ha-noi",
            selected_places=[
                SelectedPlaceContext(
                    name="Văn Miếu",
                    placeId="place-van-mieu",
                    mustVisit=True,
                )
            ],
        )
    )

    assert output.day_briefs_ready is True
    assert output.trace.status.value == "completed"


def test_main_workflow_accepts_structured_selected_places() -> None:
    statistics = FakeStatisticsProvider()
    workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=_planner(statistics),
        finder=FinderService(),
    )
    payload = MainPlanCreate.model_validate(
        {
            "destination": "Hà Nội",
            "days": 2,
            "interests": ["culture"],
            "regionKey": "vn,ha-noi",
            "selectedPlaces": [
                {
                    "placeId": "place-van-mieu",
                    "name": "Văn Miếu",
                    "mustVisit": True,
                    "priority": 1,
                    "tags": ["culture"],
                }
            ],
        }
    )

    plan = asyncio.run(workflow.run(payload))

    assert plan.macro_plan.region_key == "vn,ha-noi"
    assert "snapshotRef" not in plan.macro_plan.model_dump(by_alias=True)
    assert plan.macro_plan.day_briefs[0].allocated_selected_place_refs == [
        "place-van-mieu"
    ]
    assert plan.days[0].items[0].name == "Văn Miếu"


def test_main_workflow_accepts_confirmed_explorer_context() -> None:
    workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=_planner(FakeStatisticsProvider(place_count=0)),
        finder=FinderService(),
    )
    payload = MainPlanFromExplorerCreate.model_validate(
        {
            "intent": {
                "destination": "Hà Nội",
                "budgetLevel": "medium",
                "travelStyle": "local",
                "pace": "balanced",
                "interests": ["culture"],
            },
            "tripSpec": {
                "days": 2,
                "partySize": 3,
                "budget": {
                    "inputMode": "unknown",
                    "currency": "VND",
                    "isHardCap": False,
                    "confidence": "low",
                },
            },
            "selectedPlaces": [
                {
                    "name": "Văn Miếu",
                    "mustVisit": True,
                    "tags": ["culture"],
                    "sourceRefs": ["https://example.com/reel"],
                }
            ],
        }
    )

    plan = asyncio.run(workflow.run_from_explorer(payload))

    assert plan.status.value == "draft"
    assert plan.check_report is not None
    assert plan.check_report.status == "needs_backup"
    assert plan.days[0].items[0].name == "Văn Miếu"


def test_plan_service_uses_persisted_explorer_places_from_intake() -> None:
    main_workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=_planner(FakeStatisticsProvider(place_count=0)),
        finder=FinderService(),
    )
    service = PlanService(
        repository=PlanRepository(),
        explore_formatter=object(),  # type: ignore[arg-type]
        main_workflow=main_workflow,
        backup_workflow=object(),  # type: ignore[arg-type]
        explorer_persistence=FakeExplorerPersistence(),
    )
    payload = MainPlanFromExplorerCreate.model_validate(
        {
            "intakeId": "intake-tiktok",
            "userId": None,
            "intent": {
                "destination": "Hà Nội",
                "budgetLevel": "medium",
                "travelStyle": "local",
                "pace": "balanced",
                "interests": ["food"],
            },
            "tripSpec": {
                "days": 1,
                "partySize": 2,
                "budget": {
                    "inputMode": "unknown",
                    "currency": "VND",
                    "isHardCap": False,
                    "confidence": "low",
                },
            },
            "selectedPlaces": [],
        }
    )

    plan = asyncio.run(service.create_main_plan_from_explorer(payload))

    assert plan.days[0].items[0].name == "Bún chả Hàng Quạt"
    assert plan.days[0].items[0].source_refs == [
        "https://www.tiktok.com/@brandneweats/video/7662905162960243989"
    ]


def test_main_workflow_accepts_planning_context() -> None:
    workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=_planner(FakeStatisticsProvider(place_count=0)),
        finder=FinderService(),
        checker=OverallChecker(),
    )
    payload = PlanningContextCreate.model_validate(
        {
            "intent": {
                "destination": "Hà Nội",
                "budgetLevel": "medium",
                "travelStyle": "local",
                "pace": "balanced",
                "interests": ["culture"],
            },
            "tripSpec": {
                "days": 2,
                "partySize": 2,
                "budget": {
                    "inputMode": "unknown",
                    "currency": "VND",
                    "isHardCap": False,
                    "confidence": "low",
                },
            },
            "regionKey": "vn,ha-noi",
            "selectedPlaces": [
                {
                    "placeId": "place-van-mieu",
                    "name": "Văn Miếu",
                    "mustVisit": True,
                    "priority": 1,
                },
                {
                    "placeId": "place-ho-guom",
                    "name": "Hồ Gươm",
                    "mustVisit": True,
                    "priority": 2,
                },
            ],
        }
    )

    plan = asyncio.run(workflow.run_from_context(payload))

    assert plan.intent.days == 2
    assert len(plan.days) == 2
    assert plan.days[0].items[0].place_id == "place-van-mieu"
    assert plan.days[1].items[0].place_id == "place-ho-guom"
    assert plan.status.value == "draft"
    assert plan.check_report is not None
    assert plan.check_report.status == "needs_backup"


def test_main_workflow_keeps_plan_draft_when_place_is_unscheduled() -> None:
    workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=_planner(FakeStatisticsProvider()),
        finder=FinderService(),
        checker=OverallChecker(),
    )
    payload = MainPlanCreate.model_validate(
        {
            "destination": "Hà Nội",
            "days": 1,
            "pace": "balanced",
            "regionKey": "vn,ha-noi",
            "selectedPlaces": [
                {
                    "placeId": f"place-{index}",
                    "name": f"Place {index}",
                    "mustVisit": True,
                }
                for index in range(1, 5)
            ],
        }
    )

    plan = asyncio.run(workflow.run(payload))

    assert plan.status.value == "draft"
    assert plan.check_report is not None
    assert plan.check_report.status == "needs_backup"
    assert plan.unscheduled_places[0].place_id == "place-4"
    assert plan.unscheduled_places[0].reason_code == "no_day_capacity"


def test_main_workflow_rejects_empty_catalog_and_no_confirmed_places() -> None:
    workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=_planner(FakeStatisticsProvider(place_count=0)),
        finder=FinderService(),
        checker=OverallChecker(),
    )
    payload = MainPlanCreate(
        destination="Hà Nội",
        days=1,
        selectedPlaces=[],
    )

    with pytest.raises(AppError) as captured:
        asyncio.run(workflow.run(payload))

    assert captured.value.code == "PLANNER_INPUT_INSUFFICIENT"
    assert captured.value.status_code == 422


def test_backup_preserves_optional_confirmed_place() -> None:
    statistics = FakeStatisticsProvider()
    planner = _planner(statistics)
    finder = FinderService()
    main_workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=planner,
        finder=finder,
        checker=OverallChecker(),
    )
    backup_workflow = BackupPlanWorkflow(
        planner=planner,
        finder=finder,
        validator=BackupValidator(),
    )
    main_plan = asyncio.run(
        main_workflow.run(
            MainPlanCreate.model_validate(
                {
                    "destination": "Hà Nội",
                    "days": 1,
                    "regionKey": "vn,ha-noi",
                    "selectedPlaces": [
                        {
                            "placeId": "optional-place",
                            "name": "Optional Place",
                            "mustVisit": False,
                            "sourceRefs": ["source-1"],
                            "tags": ["indoor"],
                        }
                    ],
                }
            )
        )
    )

    backup_plan, _ = asyncio.run(
        backup_workflow.run(
            main_plan,
            BackupPlanCreate(reason="test optional preservation"),
        )
    )

    preserved = [
        item
        for day in backup_plan.days
        for item in day.items
        if item.source == "selected_place"
    ]
    assert [item.name for item in preserved] == ["Optional Place"]
    assert preserved[0].source_refs == ["source-1"]
    assert main_plan.days[0].items[0].place_type == "selected_place"


def test_backup_avoid_outdoor_uses_tags_not_place_name() -> None:
    statistics = FakeStatisticsProvider()
    planner = _planner(statistics)
    finder = FinderService()
    main_workflow = MainPlanWorkflow(
        explorer=ExplorerService(),
        planner=planner,
        finder=finder,
        checker=OverallChecker(),
    )
    backup_workflow = BackupPlanWorkflow(
        planner=planner,
        finder=finder,
        validator=BackupValidator(),
    )
    main_plan = asyncio.run(
        main_workflow.run(
            MainPlanCreate.model_validate(
                {
                    "destination": "Hà Nội",
                    "days": 1,
                    "regionKey": "vn,ha-noi",
                    "selectedPlaces": [
                        {
                            "placeId": "beach-stop",
                            "name": "Coastal Stop",
                            "mustVisit": False,
                            "tags": ["beach", "outdoor"],
                        }
                    ],
                }
            )
        )
    )

    backup_plan, _ = asyncio.run(
        backup_workflow.run(
            main_plan,
            BackupPlanCreate(avoidOutdoor=True),
        )
    )

    assert all(
        item.name != "Coastal Stop"
        for day in backup_plan.days
        for item in day.items
    )
    assert "avoid_outdoor" in backup_plan.intent.constraints


def _planner(statistics: "FakeStatisticsProvider") -> PlannerService:
    return PlannerService(statistics, FakePlannerLLM())


class FakePlannerLLM:
    async def generate_json(self, system_prompt: str, user_payload: str) -> str:
        envelope = json.loads(user_payload)
        planner_input = envelope["plannerInput"]
        intent = planner_input["intent"]
        trip_spec = planner_input["tripSpec"]
        context = planner_input["regionContext"]
        selected = sorted(
            planner_input["selectedPlaces"],
            key=lambda place: (
                not place["mustVisit"],
                place["priority"],
                place["name"],
            ),
        )
        capacity = {
            "relaxed": 2,
            "balanced": 3,
            "packed": 5,
        }[intent["pace"]]
        allocation_order = [
            day
            for _ in range(capacity)
            for day in range(1, trip_spec["days"] + 1)
        ]
        allocated_by_day = {
            day: [] for day in range(1, trip_spec["days"] + 1)
        }
        unallocated = []
        avoided = {name.casefold() for name in intent["avoidPlaces"]}
        excluded = {
            name.casefold()
            for name in planner_input["planState"]["excludedPlaceNames"]
        }
        allocation_index = 0
        for place in selected:
            stable_ref = place.get("placeId") or place["name"]
            if place["name"].casefold() in avoided:
                unallocated.append(
                    {
                        "place": place,
                        "reasonCode": "avoided_by_user",
                        "reason": "Place is explicitly avoided.",
                    }
                )
                continue
            if place["name"].casefold() in excluded:
                unallocated.append(
                    {
                        "place": place,
                        "reasonCode": "excluded_by_plan_state",
                        "reason": "Place is excluded from this planning scope.",
                    }
                )
                continue
            if allocation_index >= len(allocation_order):
                unallocated.append(
                    {
                        "place": place,
                        "reasonCode": "no_day_capacity",
                        "reason": "No remaining macro-plan capacity.",
                    }
                )
                continue
            day = allocation_order[allocation_index]
            allocated_by_day[day].append(stable_ref)
            allocation_index += 1

        candidate_areas = context["plannerSignals"].get("candidateAreas", [])
        target_region = (
            candidate_areas[0]["regionKey"]
            if candidate_areas
            else context["regionKey"]
        )
        focus = (
            intent["interests"]
            or context["plannerSignals"].get("dominantTags", [])
            or ["local"]
        )
        day_briefs = [
            {
                "day": day,
                "theme": f"Ngày {day}: {focus[(day - 1) % len(focus)]}",
                "targetArea": target_region.split(",")[-1],
                "targetRegionKey": target_region,
                "focusTags": list(
                    dict.fromkeys(
                        [
                            focus[(day - 1) % len(focus)],
                            *context["plannerSignals"].get("dominantTags", [])[:2],
                        ]
                    )
                ),
                "pace": intent["pace"],
                "dayPartGoals": {
                    "morning": "Khám phá theo chủ đề.",
                    "lunch": "Ăn trưa linh hoạt.",
                    "afternoon": "Tiếp tục trong cùng khu vực.",
                    "evening": "Giữ lịch linh hoạt.",
                },
                "allocatedSelectedPlaceRefs": allocated_by_day[day],
                "notes": ["Finder sẽ chọn địa điểm và giờ cụ thể."],
            }
            for day in range(1, trip_spec["days"] + 1)
        ]
        return json.dumps(
            {
                "macroPlan": {
                    "title": f"Kế hoạch {intent['destination']}",
                    "destination": intent["destination"],
                    "regionKey": context["regionKey"],
                    "dayBriefs": day_briefs,
                },
                "unallocatedSelectedPlaces": unallocated,
                "assumptions": ["Generated by test LLM."],
                "warnings": [],
            },
            ensure_ascii=False,
        )


class RecordingPlannerLLM(FakePlannerLLM):
    def __init__(self) -> None:
        self.system_prompt = ""
        self.user_payload = ""

    async def generate_json(self, system_prompt: str, user_payload: str) -> str:
        self.system_prompt = system_prompt
        self.user_payload = user_payload
        return await super().generate_json(system_prompt, user_payload)


class FakeStatisticsProvider:
    def __init__(self, *, place_count: int = 20) -> None:
        self.place_count = place_count
        self.requested_region_keys: list[str] = []

    def get_for_planner(
        self,
        region_key: str,
        *,
        force: bool = False,
    ) -> PlannerRegionStatisticsResult:
        self.requested_region_keys.append(region_key)
        regions = []
        if self.place_count:
            regions = [
                {
                    "regionKey": region_key,
                    "placeCount": self.place_count,
                    "activePlaceCount": self.place_count,
                    "countsByType": {"museum": 4, "restaurant": 8},
                    "tagCounts": {"culture": 4, "food": 8},
                    "timeOfDayCoverage": {
                        "morning": 10,
                        "lunch": 8,
                        "afternoon": 10,
                        "evening": 3,
                        "placesWithKnownHours": 12,
                    },
                    "dataQuality": {
                        "missingOpeningHours": 8,
                        "staleOperationalData": 0,
                    },
                    "areaProfiles": [
                        {
                            "regionKey": "vn,ha-noi,hoan-kiem",
                            "placeCount": 12,
                            "topTags": ["food", "culture"],
                        }
                    ],
                    "plannerSignals": {
                        "dominantTags": ["food", "culture"],
                        "strongDayParts": ["morning", "afternoon"],
                        "weakDayParts": ["evening"],
                        "candidateAreas": [
                            {
                                "regionKey": "vn,ha-noi,hoan-kiem",
                                "placeCount": 12,
                                "topTags": ["food", "culture"],
                            }
                        ],
                    },
                }
            ]
        return PlannerRegionStatisticsResult(
            status="cached",
            region_key=region_key,
            regions=regions,
            snapshot_id="snapshot-3",
            catalog_version=3,
            algorithm_version="auto_statistics_v2_1",
            generated_at="2026-07-28T10:00:00+00:00",
            source_fingerprint="fingerprint",
        )


class FakeExplorerPersistence:
    def load_must_places(
        self,
        intake_id: str,
        user_id: str | None,
    ) -> list[SelectedPlaceCreate]:
        assert intake_id == "intake-tiktok"
        assert user_id is None
        return [
            SelectedPlaceCreate(
                name="Bún chả Hàng Quạt",
                mustVisit=True,
                tags=["food"],
                sourceRefs=[
                    "https://www.tiktok.com/@brandneweats/video/7662905162960243989"
                ],
            )
        ]


def _intent() -> TravelIntent:
    return TravelIntent(
        destination="Hà Nội",
        days=2,
        budget=BudgetLevel.medium,
        travelStyle="local",
        pace=TravelPace.balanced,
        interests=["culture", "food"],
    )
