// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/admin/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/listings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/places/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/places">> = Specific
  const handler = {} as typeof import("../../src/app/admin/places/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/creator/listings/[listingId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/listings/[listingId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/creator/listings/[listingId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/creator/listings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/listings/new">> = Specific
  const handler = {} as typeof import("../../src/app/creator/listings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/creator/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/listings">> = Specific
  const handler = {} as typeof import("../../src/app/creator/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../src/app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/groups/[groupId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups/[groupId]">> = Specific
  const handler = {} as typeof import("../../src/app/groups/[groupId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/listings/[listingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listings/[listingId]">> = Specific
  const handler = {} as typeof import("../../src/app/listings/[listingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[orderId]/mock-momo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]/mock-momo">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[orderId]/mock-momo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[orderId]/result/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]/result">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[orderId]/result/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planner">> = Specific
  const handler = {} as typeof import("../../src/app/planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reels">> = Specific
  const handler = {} as typeof import("../../src/app/reels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
