from typing import Protocol


class EmbeddingClient(Protocol):
    @property
    def model(self) -> str: ...

    @property
    def dimensions(self) -> int: ...

    def embed_query(self, text: str) -> list[float]: ...

    def embed_document(self, text: str, *, title: str | None = None) -> list[float]: ...
